[package]
name = "bruma-render"
description = "Renderizado de Bruma con wgpu (WebGPU con respaldo WebGL2)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
wgpu.workspace = true
bytemuck.workspace = true
log.workspace = true

[dev-dependencies]
naga = { version = "30", features = ["wgsl-in"] }
